<?php
const TAINTED_VARS = array(
  '_GET',
  '_POST',
  '_REQUEST',
  '_FILES',
  '_COOKIE',
  '_SESSION',
  '_SERVER'
);


const INSECURE_FUNCTIONS = array(
  // XSS
  'PRINT_EXPR' => 'XSS',
  'print' => 'XSS',
  'echo' => 'XSS',
  'print_r' => 'XSS',
  'exit' => 'XSS',
  'die' => 'XSS',
  'printf' => 'XSS',
  // Header Injection
  'header' => 'Header Injection',
  // Code Execution
  'EVAL_EXPR' => 'Code Execution',
  'assert' => 'Code Execution',
  'create_function' => 'Code Execution',
  'eval' => 'Code Execution',
  'mb_ereg_replace' => 'Code Execution',
  'mb_eregi_replace' => 'Code Execution',
  'preg_filter' => 'Code Execution',
  'preg_replace' => 'Code Execution',
  'preg_replace_callback' => 'Code Execution',
  // File Inclusion
  'INCLUDE_EXPR' => 'File Inclusion',
  'include' => 'File Inclusion',
  'include_once' => 'File Inclusion',
  'require' => 'File Inclusion',
  'require_once' => 'File Inclusion',
  'set_include_path' => 'File Inclusion',
  'virtual' => 'File Inclusion',
  // File Disclosure
  'bzread' => 'File Disclosure',
  'bzflush' => 'File Disclosure',
  'dio_read' => 'File Disclosure',
  'eio_readdir' => 'File Disclosure',
  'fdf_open' => 'File Disclosure',
  'file' => 'File Disclosure',
  'file_get_contents' => 'File Disclosure',
  'finfo_file' => 'File Disclosure',
  'fflush' => 'File Disclosure',
  'fgetc' => 'File Disclosure',
  'fgetcsv' => 'File Disclosure',
  'fgets' => 'File Disclosure',
  'fgetss' => 'File Disclosure',
  'fread' => 'File Disclosure',
  'fpassthru' => 'File Disclosure',
  'fscanf' => 'File Disclosure',
  'ftok' => 'File Disclosure',
  'get_meta_tags' => 'File Disclosure',
  'glob' => 'File Disclosure',
  'gzfile' => 'File Disclosure',
  'gzgetc' => 'File Disclosure',
  'gzgets' => 'File Disclosure',
  'gzgetss' => 'File Disclosure',
  'gzread' => 'File Disclosure',
  'gzpassthru' => 'File Disclosure',
  'highlight_file' => 'File Disclosure',
  'imagecreatefrompng' => 'File Disclosure',
  'imagecreatefromjpg' => 'File Disclosure',
  'imagecreatefromgif' => 'File Disclosure',
  'imagecreatefromgd2' => 'File Disclosure',
  'imagecreatefromgd2part' => 'File Disclosure',
  'imagecreatefromgd' => 'File Disclosure',
  'opendir' => 'File Disclosure',
  'parse_ini_file' => 'File Disclosure',
  'php_strip_whitespace' => 'File Disclosure',
  'readfile' => 'File Disclosure',
  'readgzfile' => 'File Disclosure',
  'readlink' => 'File Disclosure',
  'scandir' => 'File Disclosure',
  'show_source' => 'File Disclosure',
  'simplexml_load_file' => 'File Disclosure',
  'stream_get_contents' => 'File Disclosure',
  'stream_get_line' => 'File Disclosure',
  'xdiff_file_bdiff' => 'File Disclosure',
  'xdiff_file_bpatch' => 'File Disclosure',
  'xdiff_file_diff_binary' => 'File Disclosure',
  'xdiff_file_diff' => 'File Disclosure',
  'xdiff_file_merge3' => 'File Disclosure',
  'xdiff_file_patch_binary' => 'File Disclosure',
  'xdiff_file_patch' => 'File Disclosure',
  'xdiff_file_rabdiff' => 'File Disclosure',
  'yaml_parse_file' => 'File Disclosure',
  'zip_open' => 'File Disclosure',
  // File Manipulation
  'bzwrite' => 'File Manipulation',
  'chmod' => 'File Manipulation',
  'chgrp' => 'File Manipulation',
  'chown' => 'File Manipulation',
  'copy' => 'File Manipulation',
  'dio_write' => 'File Manipulation',
  'eio_chmod' => 'File Manipulation',
  'eio_chown' => 'File Manipulation',
  'eio_mkdir' => 'File Manipulation',
  'eio_mknod' => 'File Manipulation',
  'eio_rmdir' => 'File Manipulation',
  'eio_write' => 'File Manipulation',
  'eio_unlink' => 'File Manipulation',
  'error_log' => 'File Manipulation',
  'event_buffer_write' => 'File Manipulation',
  'file_put_contents' => 'File Manipulation',
  'fputcsv' => 'File Manipulation',
  'fputs' => 'File Manipulation',
  'fprintf' => 'File Manipulation',
  'ftruncate' => 'File Manipulation',
  'fwrite' => 'File Manipulation',
  'gzwrite' => 'File Manipulation',
  'gzputs' => 'File Manipulation',
  'loadXML' => 'File Manipulation',
  'mkdir' => 'File Manipulation',
  'move_uploaded_file' => 'File Manipulation',
  'posix_mknod' => 'File Manipulation',
  'recode_file' => 'File Manipulation',
  'rename' => 'File Manipulation',
  'rmdir' => 'File Manipulation',
  'shmop_write' => 'File Manipulation',
  'touch' => 'File Manipulation',
  'unlink' => 'File Manipulation',
  'vfprintf' => 'File Manipulation',
  'xdiff_file_bdiff' => 'File Manipulation',
  'xdiff_file_bpatch' => 'File Manipulation',
  'xdiff_file_diff_binary' => 'File Manipulation',
  'xdiff_file_diff' => 'File Manipulation',
  'xdiff_file_merge3' => 'File Manipulation',
  'xdiff_file_patch_binary' => 'File Manipulation',
  'xdiff_file_patch' => 'File Manipulation',
  'xdiff_file_rabdiff' => 'File Manipulation',
  'yaml_emit_file' => 'File Manipulation',
  // Command Execution
  'backticks' => 'Command Execution',
  'exec' => 'Command Execution',
  'expect_popen' => 'Command Execution',
  'passthru' => 'Command Execution',
  'pcntl_exec' => 'Command Execution',
  'popen' => 'Command Execution',
  'proc_open' => 'Command Execution',
  'shell_exec' => 'Command Execution',
  'system' => 'Command Execution',
  'mail' => 'Command Execution',
  'mb_send_mail' => 'Command Execution',
  'w32api_invoke_function' => 'Command Execution',
  'w32api_register_function' => 'Command Execution',
  // SQL Injection
  'dba_open' => 'SQL Injection',
  'dba_popen' => 'SQL Injection',
  'dba_insert' => 'SQL Injection',
  'dba_fetch' => 'SQL Injection',
  'dba_delete' => 'SQL Injection',
  'dbx_query' => 'SQL Injection',
  'odbc_do' => 'SQL Injection',
  'odbc_exec' => 'SQL Injection',
  'odbc_execute' => 'SQL Injection',
  'db2_exec' => 'SQL Injection',
  'db2_execute' => 'SQL Injection',
  'fbsql_db_query' => 'SQL Injection',
  'fbsql_query' => 'SQL Injection',
  'ibase_query' => 'SQL Injection',
  'ibase_execute' => 'SQL Injection',
  'ifx_query' => 'SQL Injection',
  'ifx_do' => 'SQL Injection',
  'ingres_query' => 'SQL Injection',
  'ingres_execute' => 'SQL Injection',
  'ingres_unbuffered_query' => 'SQL Injection',
  'msql_db_query' => 'SQL Injection',
  'msql_query' => 'SQL Injection',
  'msql' => 'SQL Injection',
  'mssql_query' => 'SQL Injection',
  'mssql_execute' => 'SQL Injection',
  'mysql_db_query' => 'SQL Injection',
  'mysql_query' => 'SQL Injection',
  'mysql_unbuffered_query' => 'SQL Injection',
  'mysqli_stmt_execute' => 'SQL Injection',
  'mysqli_query' => 'SQL Injection',
  'mysqli_real_query' => 'SQL Injection',
  'mysqli_master_query' => 'SQL Injection',
  'oci_execute' => 'SQL Injection',
  'ociexecute' => 'SQL Injection',
  'ovrimos_exec' => 'SQL Injection',
  'ovrimos_execute' => 'SQL Injection',
  'ora_do' => 'SQL Injection',
  'ora_exec' => 'SQL Injection',
  'pg_query' => 'SQL Injection',
  'pg_send_query' => 'SQL Injection',
  'pg_send_query_params' => 'SQL Injection',
  'pg_send_prepare' => 'SQL Injection',
  'pg_prepare' => 'SQL Injection',
  'sqlite_open' => 'SQL Injection',
  'sqlite_popen' => 'SQL Injection',
  'sqlite_array_query' => 'SQL Injection',
  'arrayQuery' => 'SQL Injection',
  'singleQuery' => 'SQL Injection',
  'sqlite_query' => 'SQL Injection',
  'sqlite_exec' => 'SQL Injection',
  'sqlite_single_query' => 'SQL Injection',
  'sqlite_unbuffered_query' => 'SQL Injection',
  'sybase_query' => 'SQL Injection',
  'sybase_unbuffered_query' => 'SQL Injection',
  // XPath Injection
  'xpath_eval' => 'XPath Injection',
  'xpath_eval_expression' => 'XPath Injection',
  'xptr_eval' => 'XPath Injection',
  // LDAP Injection
  'ldap_add' => 'LDAP Injection',
  'ldap_delete' => 'LDAP Injection',
  'ldap_list' => 'LDAP Injection',
  'ldap_read' => 'LDAP Injection',
  'ldap_search' => 'LDAP Injection',
  // PHP Object Injection
  'unserialize' => 'PHP Object Injection',
  'yaml_parse' => 'PHP Object Injection',
);


const SANITIZERS = array(
  // ALL
  'intval' => 'ALL',
  'floatval' => 'ALL',
  'doubleval' => 'ALL',
  'filter_input' => 'ALL',
  'urlencode' => 'ALL',
  'rawurlencode' => 'ALL',
  'round' => 'ALL',
  'floor' => 'ALL',
  'strlen' => 'ALL',
  'strrpos' => 'ALL',
  'strpos' => 'ALL',
  'strftime' => 'ALL',
  'strtotime' => 'ALL',
  'md5' => 'ALL',
  'md5_file' => 'ALL',
  'sha1' => 'ALL',
  'sha1_file' => 'ALL',
  'crypt' => 'ALL',
  'crc32' => 'ALL',
  'hash' => 'ALL',
  'mhash' => 'ALL',
  'hash_hmac' => 'ALL',
  'password_hash' => 'ALL',
  'mcrypt_encrypt' => 'ALL',
  'mcrypt_generic' => 'ALL',
  'base64_encode' => 'ALL',
  'ord' => 'ALL',
  'sizeof' => 'ALL',
  'count' => 'ALL',
  'bin2hex' => 'ALL',
  'levenshtein' => 'ALL',
  'abs' => 'ALL',
  'bindec' => 'ALL',
  'decbin' => 'ALL',
  'dechex' => 'ALL',
  'decoct' => 'ALL',
  'hexdec' => 'ALL',
  'rand' => 'ALL',
  'max' => 'ALL',
  'min' => 'ALL',
  'metaphone' => 'ALL',
  'tempnam' => 'ALL',
  'soundex' => 'ALL',
  'money_format' => 'ALL',
  'number_format' => 'ALL',
  'date_format' => 'ALL',
  'filetype' => 'ALL',
  'nl_langinfo' => 'ALL',
  'bzcompress' => 'ALL',
  'convert_uuencode' => 'ALL',
  'gzdeflate' => 'ALL',
  'gzencode' => 'ALL',
  'gzcompress' => 'ALL',
  'http_build_query' => 'ALL',
  'lzf_compress' => 'ALL',
  'zlib_encode' => 'ALL',
  'imap_binary' => 'ALL',
  'iconv_mime_encode' => 'ALL',
  'bson_encode' => 'ALL',
  'sqlite_udf_encode_binary' => 'ALL',
  'session_name' => 'ALL',
  'readlink' => 'ALL',
  'getservbyport' => 'ALL',
  'getprotobynumber' => 'ALL',
  'gethostname' => 'ALL',
  'gethostbynamel' => 'ALL',
  'gethostbyname' => 'ALL',
  // XSS
  'htmlentities' => 'XSS',
  'htmlspecialchars' => 'XSS',
  'highlight_string' => 'XSS',
  'esc_html' => 'XSS',
  'esc_url' => 'XSS',
  'esc_js' => 'XSS',
  'esc_attr' => 'XSS',
  'esc_textarea' => 'XSS',
  'esc_html__' => 'XSS',
  'esc_html_e' => 'XSS',
  'esc_html_x' => 'XSS',
  'esc_attr__' => 'XSS',
  'esc_attr_e' => 'XSS',
  'esc_attr_x' => 'XSS'
);

define("PHP_INTERNAL_FUNCTIONS", get_defined_functions()['internal']);

const WP_HOOKS = array('add_filter', 'add_action');
